insert into users(username,email,password,phonenumber,address) values ('pavan kumar','pavankumar532425@gmail.com','532425143','7989816992','jsadoinfdngkvdfgblfdgkdflgnlfdngldfnl')
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(1,'iphone','this is item ',20000,TRUE,10,4.3)
insert into Comments(userid,itemid,comment,rating)values('pavankumar532425@gmail.com',1,'good product',4.0)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(3,'redmi note3','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(2,'iphonex','this is item ',20000,TRUE,13,4.2)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(4,'redmi note4','this is item ',20000,TRUE,20,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(5,'redmi note5','this is item ',20000,TRUE,19,4.6)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(6,'redmi note6','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(7,'redmi note7','this is item ',20000,TRUE,20,4.6)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(8,'redmi note8','this is item ',20000,TRUE,21,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(9,'redmi note9','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(10,'redmi note3 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(11,'redmi note4 pro','this is item ',20000,TRUE,19,4.7)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(12,'redmi note5 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(13,'redmi note4 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(14,'redmi note5 pro','this is item ',20000,TRUE,19,4.7)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(15,'redmi note6 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(16,'redmi note7 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(17,'redmi note8 pro','this is item ',20000,TRUE,19,4.5)
insert into items(id,itemname,itemdescription,itemprices,itemavailability,numberofitemsavailable,Itemrating) values(18,'redmi note9 pro','this is item ',20000,TRUE,19,4.5)